version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager'
    container_name: nginx-proxy-manager
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
