version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ${VOLUME_PATH}/data:/data
      - ${VOLUME_PATH}/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Nginx Proxy Manager
      - homepage.icon=nginx-proxy-manager
      - homepage.href=http://${SERVER_DOMAIN}:81
      - homepage.description=Reverse proxy
      - homepage.widget.type=npm
      - homepage.widget.url=http://${SERVER_DOMAIN}:81
      - homepage.widget.username=${USERNAME}
      - homepage.widget.password=${PASSWORD}
      - homepage.widget.fields=["enabled", "disabled", "total"]
