version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ${VOLUME_PATH}/data:/data
      - ${VOLUME_PATH}/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
