version: "3"
services:
  syncthing:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8082
      - UMASK=022
    volumes:
      - ./downloads:/downloads
      - ./appdata/config:/config
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8082
    restart: unless-stopped
