version: "3"
services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-armhf
    restart: unless-stopped
    ports:
      - 8765:8765
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - ./records:/var/lib/motioneye
