version: "3"
services:
  plex:
    container_name: plex
    network_mode: host
    image: linuxserver/plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - version=docker
    volumes:
      - ./config:/config
      - ./tvseries:/tv
      - ./movies:/movies


