version: "3.8"
services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_server
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${DB_PASSWORD}
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${VOLUME_PATH}/data:/mnt/data
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.owncloud.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.owncloud.entrypoints=web
      - traefik.http.services.owncloud.loadbalancer.server.port=8080
      - homepage.group=Media
      - homepage.name=Owncloud
      - homepage.icon=owncloud
      - homepage.href=http://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=File backup and synchronization
    security_opt:
      - no-new-privileges:true

  mariadb:
    image: mariadb:10.6.16
    container_name: owncloud_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER={DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${VOLUME_PATH}/mysql:/var/lib/mysql
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:6.2
    container_name: owncloud_redis
    restart: unless-stopped
    command: ["--databases", "1"]
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${VOLUME_PATH}/redis:/data
    security_opt:
      - no-new-privileges:true

networks:
  traefik-network:
    external: true
