version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - ${VOLUME_PATH}/etc-pihole:/etc/pihole
      - ${VOLUME_PATH}/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Pihole
      - homepage.icon=pi-hole
      - homepage.href=http://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=DNS server
      - homepage.widget.type=pihole
      - homepage.widget.url=http://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.key=${API_KEY}
      - homepage.widget.fields=["queries", "blocked", "blocked_percent", "gravity"]
