services:
  speedtest-tracker:
      image: lscr.io/linuxserver/speedtest-tracker:latest
      container_name: speedtest-tracker
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - DB_CONNECTION=sqlite
      volumes:
        - ${VOLUME_PATH}/config/speedtest-tracker:/config
      ports:
        - 8765:80
      networks:
        - traefik-network
      restart: unless-stopped
      labels:
        - traefik.enable=true
        - traefik.http.routers.speedtest-tracker.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
        - traefik.http.routers.speedtest-tracker.entrypoints=websecure
        - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
        - homepage.group=Infrastructure
        - homepage.name=Speedtest tracker
        - homepage.icon=speedtest-tracker
        - homepage.href=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
        - homepage.description=Internet performance tracking
        - homepage.widget.type=speedtest
        - homepage.widget.url=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
        - homepage.widget.fields=["download", "upload", "ping"]
      security_opt:
      - no-new-privileges:true

networks:
  traefik-network:
    external: true
