services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - DB_CONNECTION=sqlite
        volumes:
            - ${VOLUME_PATH}/config/speedtest-tracker:/config
        ports:
            - 8765:80
        networks:
            - homeserver
        restart: unless-stopped
        labels:
            # - traefik.enable=true
            # - traefik.http.routers.speedtest-tracker.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
            # - traefik.http.routers.speedtest-tracker.entrypoints=websecure
            # - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
            - homepage.enable=true
            - homepage.url=http://homeserver.tail570546.ts.net:8765
            - homepage.group=Infrastructure
            - homepage.name=Speedtest tracker
            - homepage.icon=speedtest-tracker
            - homepage.href=http://homeserver.tail570546.ts.net:8765
            # - homepage.href=${URL_SCHEME}://${SUB_DOMAIN}.${SERVER_DOMAIN}
            - homepage.description=Internet performance tracking
            - homepage.widget.type=speedtest
            # - homepage.widget.url=${URL_SCHEME}://${SUB_DOMAIN}.${SERVER_DOMAIN}
            - homepage.widget.url=http://homeserver.tail570546.ts.net:8765
            - homepage.widget.fields=["download", "upload", "ping"]
        security_opt:
            - no-new-privileges:true
networks:
    homeserver:
        external: true
