services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesResolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.myresolver.acme.dnschallenge.provider=${DNS_CHALLENGE_PROVIDER}"
      - "--certificatesResolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      #- "--certificatesResolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      CF_API_KEY: ${CF_GLOBAL_API_KEY}
      CF_API_EMAIL: ${CF_API_EMAIL}
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PATH}/letsencrypt:/letsencrypt
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.domains[0].main=${SERVER_DOMAIN}
      - traefik.http.routers.traefik.tls.domains[0].sans="*.${SERVER_DOMAIN}"
      #- traefik.http.routers.traefik.tls.domains[1].main=${WLED_DOMAIN}.${SERVER_DOMAIN}
      #- traefik.http.routers.traefik.tls.domains[1].sans="*.${WLED_DOMAIN}.${SERVER_DOMAIN}"
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      ## WLED
      #- traefik.http.routers.wled.service=wled
      #- traefik.http.routers.wled.rule=Host(`${WLED_DOMAIN}.${SERVER_DOMAIN}`)
      #- traefik.http.routers.wled.entrypoints=websecure
      #- traefik.http.services.wled.loadbalancer.servers.url="http://${WLED_IP}:80"
      #- traefik.http.routers.wled.tls.certresolver=myresolver
      ##
      - traefik.http.routers.dashboard.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - homepage.group=Infrastructure
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=Reverse proxy
      - homepage.widget.type=traefik
      - homepage.widget.url=https://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.fields=["routers", "services", "middleware"]
    security_opt:
      - no-new-privileges:true

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${SERVER_DOMAIN}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=myresolver
    security_opt:
      - no-new-privileges:true

networks:
  traefik:
    driver: bridge
    name: traefik-network
    ipam:
      config:
        - subnet: 172.23.0.0/16
