services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.web.http.redirections.entryPoint.to=web"
      #- "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      #- "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      #- "--entrypoints.websecure.address=:443"
      #- "--entrypoints.websecure.http.tls.certResolver=myresolver"
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesResolvers.myresolver.acme.email=toto@toto.fr"
      #- "--certificatesResolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      #- "443:443"
      - "8080:8080"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PATH}/letsencrypt:/letsencrypt
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      #- traefik.http.routers.traefik.tls=true
      #- traefik.http.routers.traefik.tls.domains[0].main=${SERVER_DOMAIN}
      #- traefik.http.routers.traefik.tls.domains[0].sans="*.${SERVER_DOMAIN}"
      #- traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.dashboard.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - homepage.group=Infrastructure
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=http://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=Reverse proxy
      - homepage.widget.type=traefik
      - homepage.widget.url=http://${SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.fields=["routers", "services", "middleware"]
    security_opt:
      - no-new-privileges:true

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${SERVER_DOMAIN}`, `${SERVER_IP}`)
      - traefik.http.routers.whoami.entrypoints=web
      #- traefik.http.routers.whoami.tls.certresolver=letsencrypt
    security_opt:
      - no-new-privileges:true

networks:
  traefik:
    driver: bridge
    name: traefik-network
    ipam:
      config:
        - subnet: 172.23.0.0/16
