version: "3"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8081:80
      - 4443:443
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Europe/London
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=hivian
      - MYSQL_PASSWORD=admin
    volumes:
      - ./mariadb:/config
    restart: unless-stopped
