services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - 3000:3000
    volumes:
      - ${VOLUME_PATH}/config/homepage:/app/config
    networks:
      - traefik-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.services.homepage.loadbalancer.server.port=3000

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:2375:2375
    environment:
      - CONTAINERS=1
      - POST=0
      - IMAGES=1
    networks:
      - traefik-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  traefik-network:
    external: true
