services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - LOG_LEVEL=debug
        ports:
            - 3000:3000
        volumes:
            - ${VOLUME_PATH}/config/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - homeserver
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        # labels:
        #     - traefik.enable=true
        #     - traefik.http.routers.homepage.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
        #     - traefik.http.routers.homepage.entrypoints=websecure
        #     - traefik.http.services.homepage.loadbalancer.server.port=3000

    dockerproxy:
        image: ghcr.io/tecnativa/docker-socket-proxy:latest
        container_name: dockerproxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 127.0.0.1:2375:2375
        environment:
            - CONTAINERS=1 # Allow access to viewing containers
            - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
            - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
            - POST=0 # Disallow any POST operations (effectively read-only)
        networks:
            - homeserver
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true

networks:
    homeserver:
        external: true
