version: '3.8'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696 # prowlarr
      - 6767:6767 # bazarr
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 8082:8082 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
    volumes:
      - ${VOLUME_PATH}/config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - DNS_ADDRESS=${DNS_ADDRESS}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8082
      - UMASK=022
    volumes:
      - ${VOLUME_PATH}/config/qbittorrent:/config
      - ${VOLUME_PATH}/downloads:/downloads
    depends_on:
      - gluetun
    labels:
      - autoheal=true
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: service:gluetun
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/prowlarr:/config
    depends_on:
      - qbittorrent
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: service:gluetun
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/sonarr:/config
      - ${VOLUME_PATH}/complete/tv:/tv
      - ${VOLUME_PATH}/downloads:/downloads
    depends_on:
      - prowlarr
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    network_mode: service:gluetun
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/radarr:/config
      - ${VOLUME_PATH}/complete/movies:/movies
      - ${VOLUME_PATH}/downloads:/downloads
    depends_on:
      - prowlarr
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: service:gluetun
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/bazarr:/config
      - ${VOLUME_PATH}/complete/tv:/tv
      - ${VOLUME_PATH}/complete/movies:/movies
    depends_on:
      - sonarr
      - radarr
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/jellyfin:/config
      - ${VOLUME_PATH}/complete/tv:/data/tvshows
      - ${VOLUME_PATH}/complete/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media server
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=http://${JELLYFIN_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=Watch movies and TV shows.
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://${JELLYFIN_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - ${VOLUME_PATH}/config/jellyseerr:/app/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    depends_on:
      - radarr
      - sonarr
      - jellyfin
    restart: unless-stopped
    labels:
      - homepage.group=Media server
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr
      - homepage.href=http://${JELLYSEERR_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=Request movies and TV shows.
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://${JELLYSEERR_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.key=${JELLYSEERR_API_KEY}
      - homepage.widget.fields=["pending", "approved", "available"]
