version: "3"
services:
    nginx:
        image: linuxserver/nginx
        container_name: nginx
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./config:/config
        restart: unless-stopped
