services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${VOLUME_PATH}/data:/data
        restart: unless-stopped
        networks:
            - homeserver
        labels:
            # - traefik.enable=true
            # - traefik.http.routers.portainer.rule=Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
            # - traefik.http.routers.portainer.entrypoints=websecure
            # - traefik.http.services.portainer.loadbalancer.server.port=9000
            - homepage.enable=true
            - homepage.url=http://homeserver.tail570546.ts.net:9000
            - homepage.group=Infrastructure
            - homepage.name=Portainer
            - homepage.icon=portainer
            # - homepage.href=${URL_SCHEME}://${SUB_DOMAIN}.${SERVER_DOMAIN}
            - homepage.href=http://homeserver.tail570546.ts.net:9000
            - homepage.description=Container management
            - homepage.widget.type=portainer
            - homepage.widget.url=http://homeserver.tail570546.ts.net:9000
            # - homepage.widget.url=${URL_SCHEME}://${SUB_DOMAIN}.${SERVER_DOMAIN}
            - homepage.widget.env=${ENV}
            - homepage.widget.key=${API_KEY}
            - homepage.widget.fields=["running", "stopped", "total"]
        security_opt:
            - no-new-privileges:true

networks:
    homeserver:
        external: true
